# Generated by Django 6.0 on 2026-01-15 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del acto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora')),
                ('inicio_solicitud', models.DateTimeField(blank=True, help_text='Fecha y hora de apertura de solicitudes (solo si requiere papeleta)', null=True, verbose_name='Inicio solicitud papeletas')),
                ('fin_solicitud', models.DateTimeField(blank=True, help_text='Fecha y hora de cierre de solicitudes (solo si requiere papeleta)', null=True, verbose_name='Fin solicitud papeletas')),
            ],
        ),
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(choices=[('CARIDAD', 'Caridad'), ('CULTOS_FORMACION', 'Cultos y Formación'), ('JUVENTUD', 'Juventud'), ('PATRIMONIO', 'Patrimonio'), ('PRIOSTIA', 'Priostía'), ('DIPUTACION_MAYOR_GOBIERNO', 'Diputación Mayor de Gobierno'), ('COSTALEROS', 'Costaleros'), ('ACÓLITOS', 'Acólitos')], max_length=50, unique=True, verbose_name='Nombre del área')),
            ],
        ),
        migrations.CreateModel(
            name='CuerpoPertenencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuerpo', models.CharField(choices=[('COSTALEROS', 'Costaleros'), ('NAZARENOS', 'Nazarenos'), ('DIPUTADOS', 'Diputados de tramo'), ('BRAZALETES', 'Brazaletes'), ('ACOLITOS', 'Acólitos'), ('CAPATACES', 'Capataces'), ('SANITARIOS', 'Sanitarios'), ('PRIOSTIA', 'Priostía'), ('CARIDAD_ACCION_SOCIAL', 'Caridad y Acción Social'), ('JUVENTUD', 'Juventud'), ('JUNTA_GOBIERNO', 'Junta de Gobierno')], max_length=50, unique=True, verbose_name='Nombre del cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoActo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTACION_PENITENCIA', 'Estación de Penitencia'), ('CABILDO_GENERAL', 'Cabildo General'), ('CABILDO_EXTRAORDINARIO', 'Cabildo Extraordinario'), ('VIA_CRUCIS', 'Vía Crucis'), ('QUINARIO', 'Quinario'), ('TRIDUO', 'Triduo'), ('ROSARIO_AURORA', 'Rosario de la Aurora'), ('CONVIVENCIA', 'Convivencia'), ('PROCESION_EUCARISTICA', 'Procesión Eucarística')], max_length=50, unique=True, verbose_name='Tipo de Acto')),
                ('requiere_papeleta', models.BooleanField(default=False, help_text='Marcar si este tipo de acto implica reparto de papeletas de sitio', verbose_name='¿Requiere papeleta?')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=75, unique=True, verbose_name='Nombre del tipo de puesto')),
                ('solo_junta_gobierno', models.BooleanField(default=False, help_text='Si se marca, este tipo de puesto estará restringido a miembros de la Junta de Gobierno.', verbose_name='Solo para Junta de Gobierno')),
                ('es_insignia', models.BooleanField(default=False, help_text='Marcar si este puesto se considera una insignia o vara.', verbose_name='¿Es insignia?')),
            ],
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='last_name',
        ),
        migrations.AddField(
            model_name='hermano',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='El código postal debe tener exactamente 5 dígitos numéricos.', regex='^\\d{5}$')], verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='comunidad_autonoma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comunidad Autónoma'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección postal'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='esAdmin',
            field=models.BooleanField(default=False, verbose_name='Es Administrador'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'Soltero'), ('SEPARADO', 'Separado'), ('CASADO', 'Casado'), ('VIUDO', 'Viudo')], default='SOLTERO', max_length=10, verbose_name='Estado Civil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_baja_corporacion',
            field=models.DateField(blank=True, help_text='Fecha en la que se hizo efectiva la baja (si procede).', null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_bautismo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de bautismo'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_ingreso_corporacion',
            field=models.DateField(blank=True, help_text='Fecha oficial de admisión en la nómina de la Hermandad.', null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], default='MASCULINO', max_length=10, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='lugar_bautismo',
            field=models.CharField(blank=True, help_text='Localidad o ciudad donde recibió el bautismo', max_length=100, null=True, verbose_name='Bautizado en'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='numero_registro',
            field=models.PositiveIntegerField(blank=True, help_text='Número de registro en la hermandad', null=True, unique=True, verbose_name='Número de registro'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='parroquia_bautismo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Parroquia de bautismo'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='telefono',
            field=models.CharField(default=123456789, max_length=9, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 9 dígitos numéricos.', regex='^\\d{9}$')], verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='estado_hermano',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja'), ('PENDIENTE_INGRESO', 'Pendiente de ingreso')], default='PENDIENTE_INGRESO', max_length=20, verbose_name='Estado del hermano'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='areas_interes',
            field=models.ManyToManyField(blank=True, related_name='hermanos', to='api.areainteres', verbose_name='Áreas de interés'),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Ejercicio / Año')),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Cuota de Hermano'), ('INGRESO', 'Cuota de Ingreso/Alta'), ('EXTRAORDINARIA', 'Cuota Extraordinaria')], default='ORDINARIA', max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: Cuota 2024', max_length=100)),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe (€)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('EN_REMESA', 'Enviada al banco (Remesa)'), ('PAGADA', 'Pagada'), ('DEVUELTA', 'Devuelta por el banco'), ('EXENTO', 'Exento de pago')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('DOMICILIACION', 'Domiciliación Bancaria'), ('TRANSFERENCIA', 'Transferencia')], default='DOMICILIACION', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to=settings.AUTH_USER_MODEL, verbose_name='Hermano')),
            ],
        ),
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator(message='El IBAN debe tener un formato válido (ej: ES00...). Debe comenzar por 2 letras y 2 números.', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{11,30}$')], verbose_name='IBAN')),
                ('es_titular', models.BooleanField(default=True, verbose_name='¿Es titular?')),
                ('titular_cuenta', models.CharField(blank=True, help_text='Rellenar solo si el hermano no es el titular', max_length=150, null=True, verbose_name='Nombre del titular')),
                ('periodicidad', models.CharField(choices=[('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='ANUAL', max_length=20, verbose_name='Periodicidad de cobro')),
                ('hermano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_bancarios', to=settings.AUTH_USER_MODEL, verbose_name='Hermano titular')),
            ],
        ),
        migrations.CreateModel(
            name='HermanoCuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.PositiveIntegerField(help_text='Año en el que el hermano ingresó en este cuerpo específico', verbose_name='Año de ingreso')),
                ('cuerpo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrantes', to='api.cuerpopertenencia', verbose_name='Cuerpo de pertenencia')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertenencias_cuerpos', to=settings.AUTH_USER_MODEL, verbose_name='Hermano')),
            ],
        ),
        migrations.AddField(
            model_name='hermano',
            name='cuerpos',
            field=models.ManyToManyField(blank=True, help_text='Colectivos a los que pertenece el hermano', related_name='hermanos_miembros', through='api.HermanoCuerpo', to='api.cuerpopertenencia', verbose_name='Cuerpos de pertenencia'),
        ),
        migrations.CreateModel(
            name='PapeletaSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_papeleta', models.CharField(choices=[('NO_SOLICITADA', 'No solicitada'), ('SOLICITADA', 'Solicitada'), ('EMITIDA', 'Emitida'), ('RECOGIDA', 'Recogida'), ('LEIDA', 'Leída'), ('ANULADA', 'Anulada')], default='NO_SOLICITADA', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(blank=True, help_text='Fecha y hora exacta en la que el Hermano realizó la solicitud', null=True, verbose_name='Fecha de solicitud')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('codigo_verificacion', models.CharField(help_text='Código único para validad la autenticidad', max_length=100, verbose_name='Código de verificación')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('numero_papeleta', models.PositiveIntegerField(blank=True, help_text='Número asignado tras el reparto de sitios', null=True, verbose_name='Número de Papeleta/Tramo')),
                ('es_solicitud_insignia', models.BooleanField(default=False, verbose_name='¿Es solicitud de insignia?')),
                ('acto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeletas', to='api.acto', verbose_name='Acto')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeletas', to=settings.AUTH_USER_MODEL, verbose_name='Hermano solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del puesto')),
                ('numero_maximo_asignaciones', models.PositiveIntegerField(default=1, verbose_name='Número máximo de asignaciones')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
                ('lugar_citacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lugar de citación')),
                ('hora_citacion', models.TimeField(blank=True, null=True, verbose_name='Hora de citación')),
                ('acto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos_disponibles', to='api.acto', verbose_name='Acto al que pertenece')),
                ('tipo_puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipopuesto', verbose_name='Tipo de puesto')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_prioridad', models.PositiveIntegerField(help_text='1 para la primera opción, 2 para la segunda, etc.', verbose_name='Orden de prioridad')),
                ('papeleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='api.papeletasitio', verbose_name='Papeleta asociada')),
                ('puesto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_preferencia', to='api.puesto', verbose_name='Puesto solicitado')),
            ],
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas_asignadas', to='api.puesto', verbose_name='Puesto asignado'),
        ),
        migrations.AddField(
            model_name='acto',
            name='tipo_acto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actos', to='api.tipoacto', verbose_name='Tipo de acto'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
