# Generated by Django 6.0 on 2026-01-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermano',
            name='estado_hermano',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='fecha_ingreso',
        ),
    ]
