# Generated by Django 6.0 on 2026-01-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_hermano_estado_hermano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermano',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='last_name',
        ),
    ]
