# Generated by Django 6.0 on 2026-01-03 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_hermano_first_name_remove_hermano_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], default='MASCULINO', max_length=10, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='telefono',
            field=models.CharField(default=654654654, max_length=9, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 9 dígitos numéricos.', regex='^\\d{9}$')], verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
