# Generated by Django 6.0 on 2026-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tipoacto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papeletasitio',
            name='estado_papeleta',
            field=models.CharField(choices=[('NO_SOLICITADA', 'No solicitada'), ('SOLICITADA', 'Solicitada'), ('EMITIDA', 'Emitida'), ('RECOGIDA', 'Recogida'), ('LEIDA', 'Leída'), ('ANULADA', 'Anulada'), ('NO_ASIGNADA', 'No asignada')], default='NO_SOLICITADA', max_length=20, verbose_name='Estado'),
        ),
    ]
