# Generated by Django 6.0 on 2026-01-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_papeletasitio_estado_papeleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='numero_maximo_asignaciones',
            field=models.PositiveIntegerField(default=1, verbose_name='Número máximo de asignaciones (Cupo total)'),
        ),
    ]
