# Generated by Django 6.0 on 2026-01-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hermano_genero_hermano_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
