# Generated by Django 6.0 on 2026-01-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_puesto_numero_maximo_asignaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='fin_solicitud_cirios',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de cierre de solicitudes de papeletas de sitio generales', null=True, verbose_name='Fin solicitud papeletas generales'),
        ),
        migrations.AddField(
            model_name='acto',
            name='inicio_solicitud_cirios',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de apertura de solicitudes de papeletas de sitio generales', null=True, verbose_name='Inicio solicitud papeletas generales'),
        ),
    ]
