# Generated by Django 6.0 on 2026-01-04 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hermano_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='El código postal debe tener exactamente 5 dígitos numéricos.', regex='^\\d{5}$')], verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección postal'),
        ),
    ]
