# Generated by Django 6.0 on 2026-01-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_acto_fin_solicitud_cirios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papeletasitio',
            name='codigo_verificacion',
            field=models.CharField(blank=True, help_text='Código único para validad la autenticidad', max_length=100, null=True, verbose_name='Código de verificación'),
        ),
    ]
