# Generated by Django 6.0 on 2026-01-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hermano_codigo_postal_hermano_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='comunidad_autonoma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comunidad Autónoma'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
