# Generated by Django 6.0 on 2026-01-17 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_papeletasitio_codigo_verificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Tramo 3 - Senatus', max_length=100, verbose_name='Nombre identificativo')),
                ('numero_orden', models.PositiveIntegerField(help_text='Orden posición en la calle (1, 2, 3...)', verbose_name='Número de orden')),
                ('paso', models.CharField(choices=[('CRISTO', 'Paso de Cristo / Misterio'), ('VIRGEN', 'Paso de Virgen / Palio')], default='CRISTO', max_length=20, verbose_name='Cortejo')),
                ('color_cera', models.CharField(blank=True, help_text='Ej: Tiniebla, Blanco, Rojo', max_length=50, null=True, verbose_name='Color de la cera')),
                ('acto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='api.acto', verbose_name='Acto')),
            ],
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='tramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nazarenos', to='api.tramo', verbose_name='Tramo asignado'),
        ),
    ]
