# Generated by Django 6.0 on 2026-01-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hermano_comunidad_autonoma_hermano_localidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'Soltero'), ('SEPARADO', 'Separado'), ('CASADO', 'Casado'), ('VIUDO', 'Viudo')], default='SOLTERO', max_length=10, verbose_name='Estado Civil'),
            preserve_default=False,
        ),
    ]
