# Generated by Django 6.0 on 2026-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hermano_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='fecha_bautismo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de bautismo'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='lugar_bautismo',
            field=models.CharField(blank=True, help_text='Localidad o ciudad donde recibió el bautismo', max_length=100, null=True, verbose_name='Bautizado en'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='parroquia_bautismo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Parroquia de bautismo'),
        ),
    ]
