# Generated by Django 6.0 on 2026-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tramo_papeletasitio_tramo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramo',
            name='color_cera',
        ),
        migrations.AddField(
            model_name='tramo',
            name='numero_maximo_cirios',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de nazarenos (cirios) que caben en este tramo por inventario o logística.', verbose_name='Aforo Máximo (Cirios)'),
        ),
    ]
