# Generated by Django 6.0 on 2026-01-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_hermano_fecha_bautismo_hermano_lugar_bautismo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(choices=[('CARIDAD', 'Caridad'), ('CULTOS_FORMACION', 'Cultos y Formación'), ('JUVENTUD', 'Juventud'), ('PATRIMONIO', 'Patrimonio'), ('PRIOSTIA', 'Priostía'), ('DIPUTACION_MAYOR_GOBIERNO', 'Diputación Mayor de Gobierno'), ('COSTALEROS', 'Costaleros'), ('ACÓLITOS', 'Acólitos')], max_length=50, unique=True, verbose_name='Nombre del área')),
            ],
        ),
        migrations.AddField(
            model_name='hermano',
            name='areas_interes',
            field=models.ManyToManyField(blank=True, related_name='hermanos', to='api.areainteres', verbose_name='Áreas de interés'),
        ),
    ]
