# Generated by Django 6.0 on 2026-01-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_tramo_color_cera_tramo_numero_maximo_cirios'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='cortejo_cristo',
            field=models.BooleanField(default=True, help_text='Marcar si este puesto pertenece al cortejo del Cristo. Desmarcar para Virgen/Palio.', verbose_name='¿Es cortejo de Cristo?'),
        ),
    ]
