# Generated by Django 6.0 on 2026-01-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_areainteres_hermano_areas_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='areas_interes',
            field=models.ManyToManyField(blank=True, null=True, related_name='hermanos', to='api.areainteres', verbose_name='Áreas de interés'),
        ),
    ]
