# Generated by Django 6.0 on 2026-01-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_puesto_cortejo_cristo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='modalidad',
            field=models.CharField(choices=[('TRADICIONAL', 'Tradicional (Fases separadas: Insignias luego Cirios)'), ('UNIFICADO', 'Unificado / Express (Todo en un plazo)')], default='TRADICIONAL', max_length=20, verbose_name='Modalidad de reparto'),
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='solicita_cirio_si_denegado',
            field=models.BooleanField(default=True, help_text='Si el hermano solicita insignia y no se le asigna por antigüedad, ¿desea salir de nazareno/cirio?', verbose_name='¿Desea cirio si no obtiene insignia?'),
        ),
    ]
