# Generated by Django 6.0 on 2026-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_acto_modalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papeletasitio',
            name='es_solicitud_insignia',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Es solicitud de insignia?'),
        ),
        migrations.AlterField(
            model_name='papeletasitio',
            name='solicita_cirio_si_denegado',
            field=models.BooleanField(blank=True, default=True, help_text='Si el hermano solicita insignia y no se le asigna por antigüedad, ¿desea salir de nazareno/cirio?', null=True, verbose_name='¿Desea cirio si no obtiene insignia?'),
        ),
    ]
