# Generated by Django 6.0 on 2026-01-09 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_hermano_areas_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del acto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora')),
            ],
        ),
        migrations.CreateModel(
            name='TipoActo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTACION_PENITENCIA', 'Estación de Penitencia'), ('CABILDO_GENERAL', 'Cabildo General'), ('CABILDO_EXTRAORDINARIO', 'Cabildo Extraordinario'), ('VIA_CRUCIS', 'Vía Crucis'), ('QUINARIO', 'Quinario'), ('TRIDUO', 'Triduo'), ('ROSARIO_AURORA', 'Rosario de la Aurora'), ('CONVIVENCIA', 'Convivencia')], max_length=50, unique=True, verbose_name='Tipo de Acto')),
                ('requiere_papeleta', models.BooleanField(default=False, help_text='Marcar si este tipo de acto implica reparto de papeletas de sitio', verbose_name='¿Requiere papeleta?')),
            ],
        ),
        migrations.AlterField(
            model_name='hermano',
            name='areas_interes',
            field=models.ManyToManyField(blank=True, related_name='hermanos', to='api.areainteres', verbose_name='Áreas de interés'),
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del puesto')),
                ('numero_maximo_asignaciones', models.PositiveIntegerField(default=1, verbose_name='Número máximo de asignaciones')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
                ('lugar_citacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lugar de citación')),
                ('hora_citacion', models.TimeField(blank=True, null=True, verbose_name='Hora de citación')),
                ('acto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos_disponibles', to='api.acto', verbose_name='Acto al que pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='PapeletaSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_papeleta', models.CharField(choices=[('NO_SOLICITADA', 'No solicitada'), ('SOLICITADA', 'Solicitada'), ('EMITIDA', 'Emitida'), ('RECOGIDA', 'Recogida'), ('LEIDA', 'Leída'), ('ANULADA', 'Anulada')], default='NO_SOLICITADA', max_length=20, verbose_name='Estado')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('codigo_verificacion', models.CharField(help_text='Código único para validad la autenticidad', max_length=100, verbose_name='Código de verificación')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('acto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeletas', to='api.acto', verbose_name='Acto')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeletas', to=settings.AUTH_USER_MODEL, verbose_name='Hermano solicitante')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas_asignadas', to='api.puesto', verbose_name='Puesto asignado')),
            ],
        ),
        migrations.AddField(
            model_name='acto',
            name='tipo_acto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actos', to='api.tipoacto', verbose_name='Tipo de acto'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
