# Generated by Django 6.0 on 2026-01-10 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_acto_tipoacto_alter_hermano_areas_interes_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuerpoPertenencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuerpo', models.CharField(choices=[('COSTALEROS', 'Costaleros'), ('NAZARENOS', 'Nazarenos'), ('DIPUTADOS', 'Diputados de tramo'), ('BRAZALETES', 'Brazaletes'), ('ACOLITOS', 'Acólitos'), ('CAPATACES', 'Capataces'), ('SANITARIOS', 'Sanitarios'), ('PRIOSTIA', 'Priostía'), ('CARIDAD_ACCION_SOCIAL', 'Caridad y Acción Social'), ('JUVENTUD', 'Juventud'), ('JUNTA_GOBIERNO', 'Junta de Gobierno')], max_length=50, unique=True, verbose_name='Nombre del cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='HermanoCuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.PositiveIntegerField(help_text='Año en el que el hermano ingresó en este cuerpo específico', verbose_name='Año de ingreso')),
                ('cuerpo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrantes', to='api.cuerpopertenencia', verbose_name='Cuerpo de pertenencia')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertenencias_cuerpos', to=settings.AUTH_USER_MODEL, verbose_name='Hermano')),
            ],
        ),
        migrations.AddField(
            model_name='hermano',
            name='cuerpos',
            field=models.ManyToManyField(blank=True, help_text='Colectivos a los que pertenece el hermano', related_name='hermanos_miembros', through='api.HermanoCuerpo', to='api.cuerpopertenencia', verbose_name='Cuerpos de pertenencia'),
        ),
    ]
