# Generated by Django 6.0 on 2026-01-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_papeletasitio_es_solicitud_insignia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papeletasitio',
            name='solicita_cirio_si_denegado',
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='vinculado_a',
            field=models.ForeignKey(blank=True, help_text='Hermano con el que se desea procesionar (perdiendo antigüedad)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas_vinculadas_origen', to=settings.AUTH_USER_MODEL, verbose_name='Vinculado a (Acompañante)'),
        ),
    ]
