# Generated by Django 6.0 on 2026-01-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_papeletasitio_solicita_cirio_si_denegado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papeletasitio',
            name='lado',
            field=models.CharField(blank=True, choices=[('IZQUIERDA', 'Izquierda'), ('DERECHA', 'Derecha'), ('CENTRO', 'Centro (Diputado/Enlace)')], max_length=15, null=True, verbose_name='Lado en el tramo'),
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='orden_en_tramo',
            field=models.PositiveIntegerField(blank=True, help_text='Posición relativa dentro del tramo (ej: Pareja 1, Pareja 2...)', null=True, verbose_name='Orden en el tramo'),
        ),
    ]
