# Generated by Django 6.0 on 2026-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cuerpopertenencia_hermanocuerpo_hermano_cuerpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='esAdmin',
            field=models.BooleanField(default=False, verbose_name='Es Administrador'),
        ),
    ]
