# Generated by Django 6.0 on 2026-01-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_papeletasitio_lado_papeletasitio_orden_en_tramo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acto',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('TRADICIONAL', 'Tradicional (Fases separadas: Insignias luego Cirios)'), ('UNIFICADO', 'Unificado / Express (Todo en un plazo)')], default='TRADICIONAL', max_length=20, null=True, verbose_name='Modalidad de reparto'),
        ),
    ]
