# Generated by Django 6.0 on 2026-01-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_acto_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acto',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('TRADICIONAL', 'Tradicional (Fases separadas: Insignias luego Cirios)'), ('UNIFICADO', 'Unificado / Express (Todo en un plazo)')], max_length=20, null=True, verbose_name='Modalidad de reparto'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['hermano', 'estado', 'anio'], name='idx_cuota_deuda_hermano'),
        ),
        migrations.AddConstraint(
            model_name='papeletasitio',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_papeleta__in', ['ANULADA', 'NO_ASIGNADA']), _negated=True), fields=('hermano', 'acto'), name='unique_papeleta_activa_hermano_acto'),
        ),
    ]
