# Generated by Django 6.0 on 2026-01-11 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_tipoacto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=75, unique=True, verbose_name='Nombre del tipo de puesto')),
            ],
        ),
        migrations.AddField(
            model_name='puesto',
            name='tipo_puesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.tipopuesto', verbose_name='Tipo de puesto'),
            preserve_default=False,
        ),
    ]
