# Generated by Django 6.0 on 2026-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_acto_modalidad_cuota_idx_cuota_deuda_hermano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='username',
            field=models.CharField(default='99999999A', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
