# Generated by Django 6.0 on 2026-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tipopuesto_puesto_tipo_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopuesto',
            name='solo_junta_gobierno',
            field=models.BooleanField(default=False, help_text='Si se marca, este tipo de puesto estará restringido a miembros de la Junta de Gobierno.', verbose_name='Solo para Junta de Gobierno'),
        ),
    ]
