# Generated by Django 6.0 on 2026-01-13 17:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tipopuesto_solo_junta_gobierno'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='fin_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de cierre de solicitudes (solo si requiere papeleta)', null=True, verbose_name='Fin solicitud papeletas'),
        ),
        migrations.AddField(
            model_name='acto',
            name='inicio_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de apertura de solicitudes (solo si requiere papeleta)', null=True, verbose_name='Inicio solicitud papeletas'),
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='es_solicitud_insignia',
            field=models.BooleanField(default=False, help_text='Indica si esta papeleta corresponde a una solicitud de vara, insignia o enser.', verbose_name='¿Es solicitud de insignia?'),
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='numero_papeleta',
            field=models.PositiveIntegerField(blank=True, help_text='Número asignado tras el reparto de sitios', null=True, verbose_name='Número de Papeleta/Tramo'),
        ),
        migrations.AddField(
            model_name='tipopuesto',
            name='es_insignia',
            field=models.BooleanField(default=False, help_text='Marcar si este tipo de puesto se considera una insignia, vara o enser que requiere asignación específica.', verbose_name='¿Es Insignia?'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='codigo_postal',
            field=models.CharField(default=41010, max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe tener exactamente 5 dígitos numéricos.', regex='^\\d{5}$')], verbose_name='Código postal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='comunidad_autonoma',
            field=models.CharField(default='Andalucía', max_length=100, verbose_name='Comunidad Autónoma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='direccion',
            field=models.CharField(default='Avenida de Coria, 13', max_length=255, verbose_name='Dirección postal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='fecha_bautismo',
            field=models.DateField(default=1998, verbose_name='Fecha de bautismo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='localidad',
            field=models.CharField(default='Sevilla', max_length=100, verbose_name='Localidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='lugar_bautismo',
            field=models.CharField(default='Sevilla', help_text='Localidad o ciudad donde recibió el bautismo', max_length=100, verbose_name='Bautizado en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='parroquia_bautismo',
            field=models.CharField(default='Parroquia de San Gonzalo', max_length=150, verbose_name='Parroquia de bautismo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='provincia',
            field=models.CharField(default='Sevilla', max_length=100, verbose_name='Provincia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoacto',
            name='tipo',
            field=models.CharField(choices=[('ESTACION_PENITENCIA', 'Estación de Penitencia'), ('CABILDO_GENERAL', 'Cabildo General'), ('CABILDO_EXTRAORDINARIO', 'Cabildo Extraordinario'), ('VIA_CRUCIS', 'Vía Crucis'), ('QUINARIO', 'Quinario'), ('TRIDUO', 'Triduo'), ('ROSARIO_AURORA', 'Rosario de la Aurora'), ('CONVIVENCIA', 'Convivencia'), ('PROCESION_EUCARISTICA', 'Procesión Eucarística'), ('PROCESION_EXTRAORDINARIA', 'Procesión Extraordinaria')], max_length=50, unique=True, verbose_name='Tipo de Acto'),
        ),
        migrations.CreateModel(
            name='PreferenciaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_prioridad', models.PositiveIntegerField(help_text='1 para la primera opción, 2 para la segunda, etc.', verbose_name='Orden de prioridad')),
                ('papeleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='api.papeletasitio', verbose_name='Papeleta asociada')),
                ('puesto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_preferencia', to='api.puesto', verbose_name='Puesto solicitado')),
            ],
        ),
    ]
