# Generated by Django 6.0 on 2026-02-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_hermano_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papeletasitio',
            options={'verbose_name': 'Papeleta de Sitio', 'verbose_name_plural': 'Papeletas de Sitio'},
        ),
        migrations.RemoveConstraint(
            model_name='papeletasitio',
            name='unique_papeleta_activa_hermano_acto',
        ),
    ]
