# Generated by Django 6.0 on 2026-01-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tipopuesto_solo_junta_gobierno'),
    ]

    operations = [
        migrations.AddField(
            model_name='papeletasitio',
            name='numero_papeleta',
            field=models.PositiveIntegerField(blank=True, help_text='Número asignado tras el reparto de sitios', null=True, verbose_name='Número de Papeleta/Tramo'),
        ),
        migrations.CreateModel(
            name='PreferenciaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_prioridad', models.PositiveIntegerField(verbose_name='Orden de prioridad')),
                ('papeleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.papeletasitio', verbose_name='Papeleta asociada')),
                ('puesto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.puesto', verbose_name='Puesto solicitado')),
            ],
            options={
                'verbose_name': 'Preferencia de puesto',
                'verbose_name_plural': 'Preferencias de puesto',
                'ordering': ['orden_prioridad'],
                'constraints': [models.UniqueConstraint(fields=('papeleta', 'puesto_solicitado'), name='unique_puesto_por_papeleta'), models.UniqueConstraint(fields=('papeleta', 'orden_prioridad'), name='unique_orden_por_papeleta')],
            },
        ),
    ]
