# Generated by Django 6.0 on 2026-01-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tipopuesto_solo_junta_gobierno'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='fin_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de cierre de solicitudes (solo si requiere papeleta)', null=True, verbose_name='Fin solicitud papeletas'),
        ),
        migrations.AddField(
            model_name='acto',
            name='inicio_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de apertura de solicitudes (solo si requiere papeleta)', null=True, verbose_name='Inicio solicitud papeletas'),
        ),
    ]
