# Generated by Django 6.0 on 2026-01-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tipopuesto_solo_junta_gobierno'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='fin_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de cierre de solicitudes (solo si requiere papeleta)', null=True, verbose_name='Fin solicitud papeletas'),
        ),
        migrations.AddField(
            model_name='acto',
            name='inicio_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de apertura de solicitudes (solo si requiere papeleta)', null=True, verbose_name='Inicio solicitud papeletas'),
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='numero_papeleta',
            field=models.PositiveIntegerField(blank=True, help_text='Número asignado tras el reparto de sitios', null=True, verbose_name='Número de Papeleta/Tramo'),
        ),
        migrations.CreateModel(
            name='PreferenciaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_prioridad', models.PositiveIntegerField(help_text='1 para la primera opción, 2 para la segunda, etc.', verbose_name='Orden de prioridad')),
                ('papeleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='api.papeletasitio', verbose_name='Papeleta asociada')),
                ('puesto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_preferencia', to='api.puesto', verbose_name='Puesto solicitado')),
            ],
        ),
    ]
