# Generated by Django 6.0 on 2026-01-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_acto_fin_solicitud_acto_inicio_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopuesto',
            name='es_insignia',
            field=models.BooleanField(default=False, help_text='Marcar si este tipo de puesto se considera una insignia, vara o enser que requiere asignación específica.', verbose_name='¿Es Insignia?'),
        ),
    ]
