# Generated by Django 6.0 on 2026-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_papeletasitio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='fecha_ejecucion_reparto',
            field=models.DateTimeField(blank=True, help_text='Si tiene valor, indica que el reparto automático ya se ha ejecutado.', null=True, verbose_name='Fecha ejecución reparto'),
        ),
    ]
