# Generated by Django 6.0 on 2026-01-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_acto_fin_solicitud_acto_inicio_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='es_titular',
            field=models.BooleanField(default=True, help_text='Indica si el hermano es el titular de la cuenta bancaria aportada', verbose_name='¿Es titular de la cuenta?'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='numero_hermano',
            field=models.PositiveIntegerField(blank=True, help_text='Número de orden en la hermandad', null=True, unique=True, verbose_name='Número de hermano'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='periodicidad',
            field=models.CharField(choices=[('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='TRIMESTRAL', max_length=20, verbose_name='Periodicidad de cuota'),
        ),
    ]
