# Generated by Django 6.0 on 2026-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tipopuesto_es_insignia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipopuesto',
            name='es_insignia',
        ),
        migrations.AlterField(
            model_name='tipoacto',
            name='tipo',
            field=models.CharField(choices=[('ESTACION_PENITENCIA', 'Estación de Penitencia'), ('CABILDO_GENERAL', 'Cabildo General'), ('CABILDO_EXTRAORDINARIO', 'Cabildo Extraordinario'), ('VIA_CRUCIS', 'Vía Crucis'), ('QUINARIO', 'Quinario'), ('TRIDUO', 'Triduo'), ('ROSARIO_AURORA', 'Rosario de la Aurora'), ('CONVIVENCIA', 'Convivencia'), ('PROCESION_EUCARISTICA', 'Procesión Eucarística'), ('PROCESION_EXTRAORDINARIA', 'Procesión Extraordinaria')], max_length=50, unique=True, verbose_name='Tipo de Acto'),
        ),
    ]
