# Generated by Django 6.0 on 2026-01-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_hermano_es_titular_hermano_iban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermano',
            name='numero_hermano',
        ),
        migrations.AddField(
            model_name='hermano',
            name='numero_registro',
            field=models.PositiveIntegerField(blank=True, help_text='Número de registro en la hermandad', null=True, unique=True, verbose_name='Número de registro'),
        ),
    ]
