# Generated by Django 6.0 on 2026-02-04 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_acto_fecha_ejecucion_reparto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(help_text='Contenido del comunicado. Soporta texto enriquecido si el frontend lo implementa.', verbose_name='Contenido')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('tipo_comunicacion', models.CharField(choices=[('GENERAL', 'General'), ('INFORMATIVO', 'Informativo'), ('CULTOS', 'Cultos'), ('SECRETARIA', 'Secretaría'), ('URGENTE', 'Urgente'), ('EVENTOS', 'Eventos y Caridad')], default='GENERAL', max_length=20, verbose_name='Tipo de comunicación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Autor (Emisor)')),
            ],
        ),
    ]
