# Generated by Django 6.0 on 2026-02-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_comunicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='areas_interes',
            field=models.ManyToManyField(blank=True, help_text='Seleccione las áreas a las que va dirigido este comunicado.', related_name='comunicados', to='api.areainteres', verbose_name='Áreas destinatarias'),
        ),
    ]
