# Generated by Django 6.0 on 2026-01-14 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_hermano_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='estado_hermano',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja'), ('PENDIENTE_INGRESO', 'Pendiente de ingreso')], default='PENDIENTE_INGRESO', max_length=20, verbose_name='Estado del hermano'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='iban',
            field=models.CharField(default='ES61123412341212345678', max_length=34, validators=[django.core.validators.RegexValidator(message='El IBAN debe tener un formato válido (ej: ES00...). Debe comenzar por 2 letras y 2 números.', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{11,30}$')], verbose_name='IBAN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='numero_registro',
            field=models.PositiveIntegerField(default=0, help_text='Número de registro en la hermandad', unique=True, verbose_name='Número de registro'),
            preserve_default=False,
        ),
    ]
