# Generated by Django 6.0 on 2026-01-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_hermano_estado_hermano_alter_hermano_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='numero_registro',
            field=models.PositiveIntegerField(blank=True, help_text='Número de registro en la hermandad', null=True, unique=True, verbose_name='Número de registro'),
        ),
    ]
