# Generated by Django 6.0 on 2026-02-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_areainteres_nombre_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='imagen_portada',
            field=models.ImageField(blank=True, help_text='Imagen principal de la noticia o comunicado', null=True, upload_to='comunicados/portadas/', verbose_name='Imagen de Portada'),
        ),
    ]
