# Generated by Django 6.0 on 2026-01-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_hermano_numero_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='estado_pago',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('DEVUELTO', 'Devuelto'), ('IMPAGADO', 'Impagado'), ('EXENTO', 'Exento'), ('BAJA_POR_IMPAGO', 'Baja por impago')], default='PENDIENTE', max_length=20, verbose_name='Estado de pagos'),
        ),
    ]
