# Generated by Django 6.0 on 2026-02-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_comunicado_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='areainteres',
            name='telegram_channel_id',
            field=models.CharField(blank=True, help_text='Ej: -100123456789. Deja vacío si esta área no tiene canal propio.', max_length=50, null=True, verbose_name='ID Canal Telegram'),
        ),
    ]
