# Generated by Django 6.0 on 2026-02-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_areainteres_telegram_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='areainteres',
            name='telegram_invite_link',
            field=models.URLField(blank=True, help_text='Ej: https://t.me/+AbCdEfGhIjK. Enlace para que el hermano se una al canal desde la app.', max_length=255, null=True, verbose_name='Enlace de invitación de Telegram'),
        ),
    ]
