# Generated by Django 6.0 on 2026-01-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_hermano_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='fecha_baja_corporacion',
            field=models.DateField(blank=True, help_text='Fecha en la que se hizo efectiva la baja (si procede).', null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='fecha_ingreso_corporacion',
            field=models.DateField(blank=True, help_text='Fecha oficial de admisión en la nómina de la Hermandad.', null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
