# Generated by Django 6.0 on 2026-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_areainteres_telegram_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID único del usuario en Telegram para envío de notificaciones directas.', max_length=50, null=True, verbose_name='Chat ID de Telegram'),
        ),
    ]
