# Generated by Django 6.0 on 2026-01-15 10:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_hermano_fecha_baja_corporacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermano',
            name='es_titular',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='periodicidad',
        ),
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator(message='El IBAN debe tener un formato válido (ej: ES00...). Debe comenzar por 2 letras y 2 números.', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{11,30}$')], verbose_name='IBAN')),
                ('es_titular', models.BooleanField(default=True, verbose_name='¿Es titular?')),
                ('titular_cuenta', models.CharField(blank=True, help_text='Rellenar solo si el hermano no es el titular', max_length=150, null=True, verbose_name='Nombre del titular')),
                ('periodicidad', models.CharField(choices=[('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='ANUAL', max_length=20, verbose_name='Periodicidad de cobro')),
                ('hermano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_bancarios', to=settings.AUTH_USER_MODEL, verbose_name='Hermano titular')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Ejercicio / Año')),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Cuota de Hermano'), ('INGRESO', 'Cuota de Ingreso/Alta'), ('EXTRAORDINARIA', 'Cuota Extraordinaria')], default='ORDINARIA', max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: Cuota 2024', max_length=100)),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe (€)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('EN_REMESA', 'Enviada al banco (Remesa)'), ('PAGADA', 'Pagada'), ('DEVUELTA', 'Devuelta por el banco'), ('EXENTO', 'Exento de pago')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('DOMICILIACION', 'Domiciliación Bancaria'), ('TRANSFERENCIA', 'Transferencia')], default='DOMICILIACION', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to=settings.AUTH_USER_MODEL, verbose_name='Hermano')),
            ],
            options={
                'indexes': [models.Index(fields=['hermano', 'anio'], name='api_cuota_hermano_8b6828_idx'), models.Index(fields=['estado'], name='api_cuota_estado_7f1f6b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo', 'ORDINARIA')), fields=('hermano', 'anio', 'tipo'), name='unica_cuota_ordinaria_por_anio')],
            },
        ),
    ]
