# Generated by Django 6.0 on 2026-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_hermano_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector semántico generado por Gemini para búsquedas RAG', null=True),
        ),
    ]
