# Generated by Django 6.0 on 2026-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_comunicado_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areainteres',
            name='nombre_area',
            field=models.CharField(choices=[('TODOS_HERMANOS', 'Todos los Hermanos'), ('CARIDAD', 'Caridad'), ('CULTOS_FORMACION', 'Cultos y Formación'), ('JUVENTUD', 'Juventud'), ('PATRIMONIO', 'Patrimonio'), ('PRIOSTIA', 'Priostía'), ('DIPUTACION_MAYOR_GOBIERNO', 'Diputación Mayor de Gobierno'), ('COSTALEROS', 'Costaleros'), ('ACOLITOS', 'Acólitos')], max_length=50, unique=True, verbose_name='Nombre del área'),
        ),
    ]
