# Generated by Django 6.0 on 2026-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_areainteres_nombre_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='tipo_comunicacion',
            field=models.CharField(choices=[('GENERAL', 'General'), ('INFORMATIVO', 'Informativo'), ('CULTOS', 'Cultos'), ('SECRETARIA', 'Secretaría'), ('URGENTE', 'Urgente'), ('EVENTOS', 'Eventos y Caridad')], max_length=20, verbose_name='Tipo de comunicación'),
        ),
    ]
