# Generated by Django 6.0 on 2026-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_comunicado_tipo_comunicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='lugar',
            field=models.CharField(default='Parroquia de San Gonzalo', max_length=200, verbose_name='Lugar de celebración'),
            preserve_default=False,
        ),
    ]
