# Generated by Django 6.0 on 2026-03-12 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_acto_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión'),
        ),
    ]
