# Generated by Django 6.0 on 2026-03-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_cuota_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='imagen_portada',
            field=models.ImageField(blank=True, help_text='Imagen principal del acto', null=True, upload_to='actos/portadas/', verbose_name='Imagen de Portada'),
        ),
    ]
