# Generated by Django 6.0 on 2026-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_acto_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='acto',
            name='fecha_ejecucion_cirios',
            field=models.DateTimeField(blank=True, help_text='Indica cuándo se ejecutó el reparto de cirios.', null=True, verbose_name='Fecha ejecución cirios/general'),
        ),
    ]
