# Generated by Django 6.0 on 2026-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_acto_fecha_ejecucion_cirios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='archivo_podcast',
            field=models.FileField(blank=True, help_text='Audio MP3 generado automáticamente', null=True, upload_to='comunicados/podcasts/', verbose_name='Podcast'),
        ),
    ]
