# Generated by Django 6.0 on 2026-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_comunicado_archivo_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='generar_podcast',
            field=models.BooleanField(default=False, help_text='Marque esta casilla si desea generar automáticamente un podcast a dos voces para este comunicado.', verbose_name='Generar Podcast'),
        ),
    ]
