# Generated by Django 6.0 on 2026-05-05 20:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_comunicado_generar_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, help_text='El hermano puede indicar opcionalmente por qué solicita la baja.', null=True, verbose_name='Motivo de la baja')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('DENEGADA', 'Denegada / En pausa')], default='PENDIENTE', max_length=20, verbose_name='Estado de la solicitud')),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Fecha en la que Secretaría aprueba o deniega la solicitud.', null=True, verbose_name='Fecha de resolución')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_baja', to=settings.AUTH_USER_MODEL, verbose_name='Hermano solicitante')),
            ],
        ),
    ]
