# Generated by Django 6.0 on 2026-05-10 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_solicitudbaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbancarios',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[django.core.validators.RegexValidator(message='El IBAN debe tener un formato válido (ej: ES00...). Debe comenzar por 2 letras y 2 números.', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{11,30}$')], verbose_name='IBAN'),
        ),
    ]
