# Generated by Django 6.0 on 2026-05-11 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_datosbancarios_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='hora_citacion',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de citación'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='lugar_citacion',
            field=models.CharField(default='Parroquia de San Gonzalo', max_length=150, verbose_name='Lugar de citación'),
        ),
    ]
